[package]
name = "oxur-repl"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Oxur REPL: protocol, client, and server with tiered execution"

[dependencies]
oxur-lang = { version = "0.1.0", path = "../oxur-lang" }
oxur-comp = { version = "0.1.0", path = "../oxur-comp" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
anyhow.workspace = true
