[package]
name = "cargo-oxur"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
cargo_metadata = "0.18"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2 = "0.10"
walkdir = "2.4"

oxur-comp = { path = "../oxur-comp" }
oxur-lang = { path = "../oxur-lang" }

[dev-dependencies]
tempfile.workspace = true
