//! Rust AST wrapper for REPL scaffolding
//!
//! Wraps user code with necessary boilerplate for REPL execution:
//! - Entry point functions
//! - Variable store access
//! - Export declarations
//!
//! Based on ODD-0026 Section 2.1

use thiserror::Error;

/// Wrapper errors
#[derive(Debug, Error)]
pub enum WrapperError {
    #[error("Invalid code structure: {0}")]
    InvalidCode(String),

    #[error("Variable name conflict: {0}")]
    NameConflict(String),
}

pub type Result<T> = std::result::Result<T, WrapperError>;

/// Wraps Rust code for REPL execution
///
/// Adds necessary scaffolding for dynamic library compilation and execution.
///
/// # Examples
///
/// ```
/// use oxur_repl::wrapper::RustAstWrapper;
///
/// let wrapper = RustAstWrapper::new();
///
/// let user_code = "let x = 42;\nprintln!(\"x = {}\", x);";
/// let wrapped = wrapper.wrap("test_key", user_code).unwrap();
///
/// // wrapped contains:
/// // - #[no_mangle]
/// // - pub extern "C" fn oxur_eval_test_key()
/// // - user code inside the function
/// ```
#[derive(Debug, Clone)]
pub struct RustAstWrapper {
    /// Whether to include debug information
    debug: bool,
}

impl RustAstWrapper {
    /// Create a new wrapper
    pub fn new() -> Self {
        Self { debug: false }
    }

    /// Create a new wrapper with debug mode
    pub fn with_debug(mut self, debug: bool) -> Self {
        self.debug = debug;
        self
    }

    /// Wrap user code for REPL execution
    ///
    /// # Arguments
    ///
    /// * `cache_key` - Cache key used for function naming
    /// * `user_code` - User's Rust code to wrap
    ///
    /// # Returns
    ///
    /// Complete Rust source code ready for compilation
    ///
    /// # Errors
    ///
    /// Returns error if the user code contains invalid patterns
    pub fn wrap(&self, cache_key: impl AsRef<str>, user_code: impl AsRef<str>) -> Result<String> {
        let cache_key = cache_key.as_ref();
        let user_code = user_code.as_ref();

        // Validate cache key is valid identifier
        if !is_valid_identifier(cache_key) {
            return Err(WrapperError::InvalidCode(format!(
                "Cache key must be valid identifier: {}",
                cache_key
            )));
        }

        // Generate wrapped code
        let mut wrapped = String::new();

        // Add standard imports
        wrapped.push_str("// Generated by Oxur REPL wrapper\n");
        wrapped.push_str("// Do not edit manually\n\n");

        if self.debug {
            wrapped.push_str("// DEBUG MODE ENABLED\n\n");
        }

        // Entry point function
        wrapped.push_str("#[no_mangle]\n");
        wrapped.push_str(&format!("pub extern \"C\" fn oxur_eval_{}() {{\n", cache_key));

        // User code (indented)
        for line in user_code.lines() {
            wrapped.push_str("    ");
            wrapped.push_str(line);
            wrapped.push('\n');
        }

        wrapped.push_str("}\n");

        Ok(wrapped)
    }

    /// Wrap code with variable store access
    ///
    /// For future use when integrating with VariableStore.
    /// Phase 3 stub - returns simple wrapping.
    pub fn wrap_with_store(
        &self,
        cache_key: impl AsRef<str>,
        user_code: impl AsRef<str>,
        _variables: &[String],
    ) -> Result<String> {
        // Phase 3: Simple wrapping without variable access
        // Phase 4: Will add variable store integration
        self.wrap(cache_key, user_code)
    }

    /// Extract variable definitions from user code
    ///
    /// Phase 3 stub - returns empty list.
    /// Full implementation will parse Rust code and extract let bindings.
    pub fn extract_variables(&self, _user_code: impl AsRef<str>) -> Vec<String> {
        // Phase 3 stub
        Vec::new()
    }
}

impl Default for RustAstWrapper {
    fn default() -> Self {
        Self::new()
    }
}

/// Check if a string is a valid Rust identifier
fn is_valid_identifier(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }

    let mut chars = s.chars();

    // First character must be alphabetic or underscore
    if let Some(first) = chars.next() {
        if !first.is_alphabetic() && first != '_' {
            return false;
        }
    }

    // Rest must be alphanumeric or underscore
    chars.all(|c| c.is_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_wrapper_creation() {
        let wrapper = RustAstWrapper::new();
        assert!(!wrapper.debug);
    }

    #[test]
    fn test_wrapper_with_debug() {
        let wrapper = RustAstWrapper::new().with_debug(true);
        assert!(wrapper.debug);
    }

    #[test]
    fn test_wrap_simple_code() {
        let wrapper = RustAstWrapper::new();

        let user_code = "let x = 42;";
        let wrapped = wrapper.wrap("test", user_code).expect("Wrapping failed");

        assert!(wrapped.contains("#[no_mangle]"));
        assert!(wrapped.contains("pub extern \"C\" fn oxur_eval_test()"));
        assert!(wrapped.contains("let x = 42;"));
    }

    #[test]
    fn test_wrap_multiline_code() {
        let wrapper = RustAstWrapper::new();

        let user_code = "let x = 42;\nlet y = 100;\nprintln!(\"sum = {}\", x + y);";
        let wrapped = wrapper.wrap("multiline", user_code).expect("Wrapping failed");

        assert!(wrapped.contains("let x = 42;"));
        assert!(wrapped.contains("let y = 100;"));
        assert!(wrapped.contains("println!"));
    }

    #[test]
    fn test_wrap_with_debug() {
        let wrapper = RustAstWrapper::new().with_debug(true);

        let user_code = "let x = 1;";
        let wrapped = wrapper.wrap("debug_test", user_code).expect("Wrapping failed");

        assert!(wrapped.contains("DEBUG MODE ENABLED"));
    }

    #[test]
    fn test_wrap_invalid_cache_key() {
        let wrapper = RustAstWrapper::new();

        let user_code = "let x = 1;";

        // Invalid cache keys
        assert!(wrapper.wrap("123invalid", user_code).is_err());
        assert!(wrapper.wrap("invalid-key", user_code).is_err());
        assert!(wrapper.wrap("", user_code).is_err());
    }

    #[test]
    fn test_wrap_valid_cache_keys() {
        let wrapper = RustAstWrapper::new();

        let user_code = "let x = 1;";

        // Valid cache keys
        assert!(wrapper.wrap("valid", user_code).is_ok());
        assert!(wrapper.wrap("valid_key", user_code).is_ok());
        assert!(wrapper.wrap("_valid", user_code).is_ok());
        assert!(wrapper.wrap("valid123", user_code).is_ok());
    }

    #[test]
    fn test_is_valid_identifier() {
        assert!(is_valid_identifier("valid"));
        assert!(is_valid_identifier("_valid"));
        assert!(is_valid_identifier("valid123"));
        assert!(is_valid_identifier("Valid_Identifier_123"));

        assert!(!is_valid_identifier(""));
        assert!(!is_valid_identifier("123invalid"));
        assert!(!is_valid_identifier("invalid-key"));
        assert!(!is_valid_identifier("invalid.key"));
        assert!(!is_valid_identifier("invalid key"));
    }

    #[test]
    fn test_extract_variables_stub() {
        let wrapper = RustAstWrapper::new();

        let user_code = "let x = 42;\nlet y = 100;";
        let vars = wrapper.extract_variables(user_code);

        // Phase 3 stub returns empty
        assert_eq!(vars.len(), 0);
    }

    #[test]
    fn test_wrap_with_store_stub() {
        let wrapper = RustAstWrapper::new();

        let user_code = "let x = 42;";
        let variables = vec!["x".to_string()];

        let wrapped =
            wrapper.wrap_with_store("store_test", user_code, &variables).expect("Wrapping failed");

        // Phase 3: Should work like normal wrap
        assert!(wrapped.contains("#[no_mangle]"));
        assert!(wrapped.contains("pub extern \"C\" fn oxur_eval_store_test()"));
    }

    #[test]
    fn test_default() {
        let wrapper1 = RustAstWrapper::default();
        let wrapper2 = RustAstWrapper::new();

        assert_eq!(wrapper1.debug, wrapper2.debug);
    }
}
