//! Basic code generation tests
//!
//! Tests for the foundational code generation infrastructure.

use oxur_ast::ast::*;
use oxur_ast::codegen::{generate_rust, RustCodegen};

#[test]
fn test_empty_crate_generates() {
    // Create minimal empty crate
    let crate_node = Crate {
        attrs: Vec::new(),
        items: Vec::new(),
        spans: ModSpans { inner_span: Span::DUMMY, inject_use_span: Span::DUMMY },
        id: NodeId(0),
        is_placeholder: false,
    };

    let result = generate_rust(&crate_node);
    assert!(result.is_ok(), "Empty crate should generate successfully");

    let code = result.unwrap();
    assert!(!code.is_empty(), "Generated code should not be empty");
    assert!(code.contains("Generated by Oxur"), "Should contain generator comment");
}

#[test]
fn test_codegen_new() {
    let _codegen = RustCodegen::new();
    // If this compiles and runs, the infrastructure is working
    assert_eq!(0, 0); // Dummy assertion
}

#[test]
fn test_codegen_default() {
    let _codegen = RustCodegen::default();
    // Verify Default trait implementation
    assert_eq!(0, 0); // Dummy assertion
}
